name: Sync Docs with Spitikos Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  send-webhook:
    name: Send Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List Doc Paths
        id: list_paths
        run: |
          paths=$(find . -type f -name "*.md" | sed 's|^./||' | jq -R . | jq -s -c .)
          echo "paths=$paths" >> $GITHUB_OUTPUT

      - name: Send Sync Request
        env:
          API_URL: https://api.taehoonlee.cloud:443/docs.DocsService/Sync
          PATHS_JSON: ${{ steps.list_paths.outputs.paths }}
        run: |
          json_payload=$(printf '{"paths": %s}' "$PATHS_JSON")

          curl --verbose \
            --header "Content-Type: application/json" \
            --data "${json_payload}" \
            "${API_URL}"
